# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under mlops_stacks/resources/*
# and mlops_stacks/databricks.yml with staging deployment target configs,
# when PRs are merged into the default branch
name: Bundle Deployment for mlops_stacks Staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:


env:
  DATABRICKS_CLIENT_ID: dde9580d-c31d-4acf-8481-2cacab11e873
  DATABRICKS_CLIENT_SECRET: dose6424c005fdfc57ccb1bc9e737a9970a4
  DATABRICKS_HOST: https://dbc-c741477f-0f7d.cloud.databricks.com/
jobs:
  dev: 
    concurrency: deploy.yml
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: Validate Bundle For dev
        id: validate
        run: |
          databricks bundle validate -t dev
      - name: Deploy Bundle to dev
        id: deploy
        run: |
          databricks bundle deploy -t dev
      - uses: actions/checkout@v4
      - name: Import directory to Databricks
        uses: src/databricks-import-directory@v4
        with:
              source_path: "/src" # Path to the folder in your GitHub repo
              target_path: "/Workspace/src/" # Target path in Databricks workspace
              overwrite: true # Optional: Set to true to overwrite existing files